name: api-server
run-name: Run server checks
on:
  pull_request:
    paths:
      - 'server/**'
  push:
    paths:
      - 'server/**'
    branches:
      - main
defaults:
  run:
    working-directory: server
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run lint check
        run: yarn lint
      - name: Run type check
        run: yarn typecheck
      - name: Run production build
        run: yarn build